### ISSUE TITLE
Upgrade data descriptions

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind_data_outreach#10]
- [ ] Identify investigators
- [ ] run upgrader

**Comment by Sun-flow** [comment]
Should focus instead on getting Project name/info, as that can be used to derive Investigators and also Funding Source. Use sheet: (https://app.smartsheet.com/sheets/R4GfCrXvHPJ5MjhjRvjgGRMJQxvwQg92wgcX5GP1?view=grid)

**Comment by saskiad** [comment]
@Sun-flow is this finished?

**Comment by saskiad** [comment]
Fixed the ephys assets. Still waiting on other data modalities
