### ISSUE TITLE
Write brief workshop description

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind_data_outreach#32]
Write a brief description of the workshop to distribute through the CNC and other neuro community at UW to advertise the workshop and get registration.

(see previous examples)

**Comment by leesuyee** [comment]
11/05 Su-Yee wrote the email blurb, approved by Saskia and Mathew. Sent the email blurb to Jessica who will attach the registration link and circulate to CNC. Su-Yee will forward to other listservs (Neurograd, NBio, NAPE, undergrad neuro (?))

**Comment by leesuyee** [comment]
11/06 Jessica added registration link and sent to CNC, Neuro, NBIO
