### ISSUE TITLE
Discuss schema 2.0 with larger group

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind_data_outreach#41]
When the specs are fleshed out, let's schedule time with larger Sci Comp team (and maybe a few key scientists) to discuss the proposed changes and how to implemented them.

**Comment by dbirman** [comment]
Doc is here for reference: https://alleninstitute.sharepoint.com/:w:/r/sites/NeuralDynamics/_layouts/15/Doc.aspx?sourcedoc=%7BE27B889D-27A1-4CC0-948C-10ADBE605654%7D&file=Data+Schema+2.0.docx&action=default&mobileredirect=true&DefaultItemOpen=1&ct=1731448731235&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=5acedf39-bda8-43b7-bc60-c843f23542cc&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=7b4a3e06-1a9c-4ee7-869b-cdd59a4fdd53
