### ISSUE TITLE
Scope ways to simplify schema

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind_data_outreach#6]
Two key goals:

1. Make the schema easier for scientists to understand
2. Set up the schema better for external scientists to use

Output of this will be specs for proposed changes that we can discuss with the team.

**Comment by dbirman** [comment]
- Getting rid of dynamic model creation (e.g. create_unit_with_value)
- Getting rid of PIDName/BaseName
- Collapsing classes with many optional fields into Union[] but without losing requirements 
- External scientists, how do we build extensions and what is an AIND extension value vs. something that other people are actually going to use

**Comment by dbirman** [comment]
https://github.com/AllenNeuralDynamics/aind-data-schema/issues/1056
